### ISSUE TITLE
Partial type match is sufficient (RDT-588)

### ISSUE THREAD

**Issue by defermelowie** [espressif/conventional-precommit-linter#11]
I noticed that a partial match of a type is sufficient to pass the check. For example `git commit -m "rever: some commit msg"` passes when using the configuration below.

```yaml
...
- repo: https://github.com/espressif/conventional-precommit-linter
  rev: v1.3.0
  hooks:
    - id: conventional-precommit-linter
      stages: [commit-msg]
      args:
        - --types=feat,fix,ci,refactor,revert,merge
...
```

Is this intended behavior (to allow for abbreviations)? If so it might be useful to state this in the readme since I, and pehaps others, did not expect this.
